"""Search a narrower correction guard within the fixed inference/peak-lookahead budget."""
from pathlib import Path
import json
import numpy as np
from scipy.signal import remez, freqz

ROOT = Path(__file__).resolve().parents[1]
def old_guard():
    n = np.arange(257)-128
    h = -2*(1100/48000)*np.sinc(2*(1100/48000)*n)*np.blackman(257)
    h /= -h.sum()
    h[128] += 1
    return h

def response(h, hz):
    return 20*np.log10(np.maximum(abs(freqz(h, worN=np.asarray(hz), fs=48000)[1]), 1e-30))

choices = []
# 1025 taps => group delay 512. Total 3776 + SR 1024 = 4800 samples.
# Leaves 192 future samples after rendering: 128 envelope + 2*32 kernel guard.
for passband in [400, 425, 450, 475, 500, 550, 600]:
    h = remez(1025, [0, 300, passband, 24000], [0, 1], weight=[100, 1], fs=48000, maxiter=100, grid_density=32)
    # Force exact DC rejection while preserving the symmetric response to rounding.
    h[512] -= h.sum()
    stop = response(h, np.linspace(0, 300, 3001)).max()
    ripple = np.max(np.abs(response(h, np.linspace(passband, 24000, 24001))))
    print(f"candidate taps=1025 passband_hz={passband} stop_max_db={stop:.6f} pass_ripple_db={ripple:.6f}")
    if stop <= -66 and ripple <= 0.1:
        choices.append((passband, h, stop, ripple))
        break
assert choices, "No candidate meets stopband plus passband requirements"
passband, h, stop, ripple = choices[0]
hz = [300, 500, 700, 1000, 1500]
table = [{"hz": f, "before_db": float(a), "after_db": float(b)} for f,a,b in zip(hz,response(old_guard(),hz),response(h,hz))]
print("hz before_db after_db")
for row in table:
    print(f"{row['hz']} {row['before_db']:.6f} {row['after_db']:.6f}")
print(f"selected_passband_hz={passband} total_latency_ms=100.000")
target = ROOT / "src" / "guard_coefficients.rs"
target.write_text("// Generated by tools/design_guard.py using SciPy remez; symmetric 1025-tap high-pass.\n"
                  + f"// Stopband <=300 Hz; passband >= {passband} Hz.\n"
                  + "pub const COEFFICIENTS: [f64; 1025] = [\n"
                  + "".join(f"    {value:.18e},\n" for value in h) + "];\n")
(ROOT / "guard_comparison.json").write_text(json.dumps({"passband_hz":passband,"stopband_max_db":float(stop),"ripple_db":float(ripple),"total_latency_ms":100,"correction_transfer":table},indent=2)+"\n")
